[project]
name = "SDFGS"
version = "0.1.0"

dependencies = [] 

[tool.setuptools.packages.find]
include = ["sdfgs*"]

# register the entry point of your new method here:
[project.entry-points.'nerfstudio.method_configs']
method-template = 'sdfgs.sdfgs_config:SDFGS'